spring.application.name=TrustworthyProductReviews
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always

